[build]
  # Build command - since this is a Node.js app, we'll use a custom build
  command = "npm run build"
  
  # Publish directory - where the built files will be served from
  publish = "public"
  
  # Functions directory for serverless functions (if needed)
  functions = "api"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API routes - redirect to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.com/api/:splat"
  status = 200
  force = true

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "preview"
