[build]
  # Build command - simple echo since this is a static site
  command = "echo 'Static files ready'"
  
  # Publish directory - where the built files will be served from
  publish = "public"
  
  # Node.js version
  NODE_VERSION = "18"

# Redirects for SPA routing - this is the key fix!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "preview"
